<?php
$pageTitle = 'Webisters Docs';
require_once __DIR__ . '/../../../includes/header.php';
require_once __DIR__ . '/../../../includes/sidebar.php';
?>
<div class="section" id="crypto">
<h1>Crypto</h1>
<p>Webisters Crypto Library.</p>
<ul>
    <li>
            <a href="#installation">Installation</a>
        </li>
    <li>
            <a href="#getting-started">Getting Started</a>
        </li>
    <li>
            <a href="#box">Box</a>
        </li>
    <li>
            <a href="#boxseal">BoxSeal</a>
        </li>
    <li>
            <a href="#generichash">GenericHash</a>
        </li>
    <li>
            <a href="#password">Password</a>
        </li>
    <li>
            <a href="#secretbox">SecretBox</a>
        </li>
    <li>
            <a href="#sign">Sign</a>
        </li>
    <li>
            <a href="#utils">Utils</a>
        </li>
    <li>
            <a href="#conclusion">Conclusion</a>
        </li>
</ul>
<div class="section" id="installation">
<h2>Installation</h2>
<p>The installation of this library can be done with Composer:</p>
<pre><code class="language- " >composer require Webisters/crypto
</code></pre>
</div>
<div class="section" id="getting-started">
<h2>Getting Started</h2>
<p>The Crypto library is built on top of Sodium, providing tools that simplify its
use.</p>
</div>
<div class="section" id="box">
<h2>Box</h2>
<p>The <strong>Box</strong> class allows communication with encrypted messages between two
entities.</p>
<p>For this, both must have a public and a private key, generated by their own key
pair.</p>
<p>Below we generate the key pair and keys for a user:</p>
<pre><code class="language-php " >use Framework\Crypto\Box;
$user1KeyPair = Box::makeKeyPair(); // string
$user1PublicKey = Box::makePublicKey($user1KeyPair); // string
$user1SecretKey = Box::makeSecretKey($user1KeyPair); // string
</code></pre>
<p>Then we generate the key pair and another user&#039;s keys:</p>
<pre><code class="language-php " >$user2KeyPair = Box::makeKeyPair(); // string
$user2PublicKey = Box::makePublicKey($user2KeyPair); // string
$user2SecretKey = Box::makeSecretKey($user2KeyPair); // string
</code></pre>
<p>Once that&#039;s done, let&#039;s create a box to encrypt messages from user 1 to user 2.</p>
<p>First, we create a nonce:</p>
<pre><code class="language-php " >$nonce = Box::makeNonce(); // string
</code></pre>
<p>Next, we create the Box for user 1, using the secret key for user 1 and the
public key for user 2:</p>
<pre><code class="language-php " >$user1Box = new Box($user1SecretKey, $user2PublicKey, $nonce);
</code></pre>
<p>So we can encrypt a message with the <code>encrypt</code> method:</p>
<pre><code class="language-php " >$messageFromUser1 = &#039;What is your name?&#039;;
$ciphertext1 = $user1Box-&gt;encrypt($messageFromUser1); // string
</code></pre>
<p>And it can already be decrypted by user 1, using the <code>decrypt</code> method:</p>
<pre><code class="language-php " >$messageFromUser1 = $user1Box-&gt;decrypt($ciphertext1); // What is your name?
</code></pre>
<p>For the second user to be able to decrypt the message, it is necessary for him
to create an instance of Box using his secret key, the public key of user 1 and
the same nonce used in the message:</p>
<pre><code class="language-php " >$user2Box = new Box($user2SecretKey, $user1PublicKey, $nonce);
</code></pre>
<p>With this, user 2 will be able to decrypt the ciphertext:</p>
<pre><code class="language-php " >$messageFromUser1 = $user2Box-&gt;decrypt($ciphertext1); // What is your name?
</code></pre>
<p>To respond, user 2 can create an instance of Box, using user 1&#039;s public key:</p>
<pre><code class="language-php " >$user2Box = new Box($user2SecretKey, $user1PublicKey, $nonce);
</code></pre>
<p>And then encrypt the message:</p>
<pre><code class="language-php " >$messageFromUser2 = &#039;John&#039;;
$ciphertext2 = $user2Box-&gt;encrypt($messageFromUser2); // string
</code></pre>
<p>Then the ciphertext can be decrypted by user 1:</p>
<pre><code class="language-php " >$messageFromUser2 = $user1Box-&gt;decrypt($ciphertext2); // John
</code></pre>
<p>And by user 2 himself:</p>
<pre><code class="language-php " >$messageFromUser2 = $user2Box-&gt;decrypt($ciphertext2); // John
</code></pre>
</div>
<div class="section" id="boxseal">
<h2>BoxSeal</h2>
<p><strong>BoxSeal</strong> allows you to encrypt a message so that only the recipient can
decrypt it.</p>
<p>First of all, the recipient needs to have a keypair that can be generated by
the <code>makeKeyPair</code> method:</p>
<pre><code class="language-php " >use Framework\Crypto\BoxSeal;
$keyPair = BoxSeal::makeKeyPair(); // string
</code></pre>
<p>Then it generates a public key with the <code>makePublicKey</code> method:</p>
<pre><code class="language-php " >$publicKey = BoxSeal::makePublicKey($keyPair); // string
</code></pre>
<p>And this public key will be given to whoever will encrypt the messages.</p>
<p>Below is a message being encrypted:</p>
<pre><code class="language-php " >$message = &#039;Expect Us!&#039;;
$ciphertext = BoxSeal::encrypt($message, $publicKey); // string
</code></pre>
<p>Then, when the ciphertext is delivered to the recipient, he can decrypt the
message using the <code>$keyPair</code> with the <code>decrypt</code> method:</p>
<pre><code class="language-php " >$message = BoxSeal::decrypt($ciphertext, $keyPair); // Expect Us!
</code></pre>
</div>
<div class="section" id="generichash">
<h2>GenericHash</h2>
<p>The <strong>GenericHash</strong> class allows verifying messages through signatures.</p>
<p>First, you must generate a key with the <code>makeKey</code> method:</p>
<pre><code class="language-php " >use Framework\Crypto\GenericHash;
$key = GenericHash::makeKey(); // string
</code></pre>
<p>Once this is done, it is possible to generate signatures for messages. Let&#039;s
look at the following example:</p>
<pre><code class="language-php " >$genericHash = new GenericHash($key);
$message = &#039;Hello, friend&#039;;
$signature = $genericHash-&gt;signature($message); // string
</code></pre>
<p>And then you can perform the verification:</p>
<pre><code class="language-php " >if ($genericHash-&gt;verify($message, $signature)) {
    echo &#039;Message is verified.&#039;;
} else {
    echo &#039;Error: Message is not verified.&#039;;
}
</code></pre>
</div>
<div class="section" id="password">
<h2>Password</h2>
<p>With the <strong>Password</strong> class it is possible to generate hashes and verify
passwords.</p>
<p>Let&#039;s see how to generate a hash:</p>
<pre><code class="language-php " >use Framework\Crypto\Password;
$password = &#039;iloveyou&#039;;
$hash = Password::hash($password); // string
</code></pre>
<p>The hash can be saved for future verification with the user&#039;s password, it is
97 characters long.</p>
<p>To verify that the password is valid, comparing it with the saved hash, you can
use the <code>verify</code> method:</p>
<pre><code class="language-php " >Password::verify($password, $hash); // bool
</code></pre>
<p>If it returns <code>true</code>, the password is correct.</p>
<p>The <code>hash</code> method has two parameters for setting <a href="#limits">Limits</a>:</p>
<pre><code class="language-php " >$opslimit = Password::LIMIT_INTERACTIVE;
$memlimit = Password::LIMIT_MODERATE;
$hash = Password::hash($password, $opslimit, $memlimit); // string
</code></pre>
<p>When limits change, it may be necessary to recreate a valid hash to store.</p>
<p>To find out if you need to create a new hash, use the <code>needsRehash</code> method:</p>
<pre><code class="language-php " >Password::needsRehash($hash); // bool
</code></pre>
<p>It also has parameters to pass the limits of operations and memory:</p>
<pre><code class="language-php " >if (Password::needsRehash($hash, Password::LIMIT_MODERATE)) {
    $hash = Password::hash($password, Password::LIMIT_MODERATE);
}
</code></pre>
<div class="section" id="limits">
<h3>Limits</h3>
<p>The Password class has three constants that must be used to set the number of
CPU operations or memory usage.</p>
<p>These values can be set in the methods of the class at each call or set in
properties by the <code>setOpsLimit</code> and <code>setMemLimit</code> methods:</p>
<pre><code class="language-php " >Password::setOpsLimit(Password::LIMIT_SENSITIVE); // void
Password::setMemLimit(Password::LIMIT_MODERATE); // void
</code></pre>
<div class="section" id="limit-interactive">
<h4>LIMIT_INTERACTIVE</h4>
<p>Used to set operations or memory limit as interactive.</p>
<p>It enables the use of 2 CPU operations or 64 MB RAM.</p>
</div>
<div class="section" id="limit-moderate">
<h4>LIMIT_MODERATE</h4>
<p>Used to set operations or memory limit as moderate.</p>
<p>It enables the use of 3 CPU operations or 256 MB RAM.</p>
</div>
<div class="section" id="limit-sensitive">
<h4>LIMIT_SENSITIVE</h4>
<p>Used to set operations or memory limit as sensitive.</p>
<p>It enables the use of 4 CPU operations or 1 GB RAM.</p>
</div>
</div>
<div class="section" id="secretbox">
<h2>SecretBox</h2>
<p>The <strong>SecretBox</strong> class allows you to encrypt and decrypt messages through a key
and a nonce.</p>
<p>First, you must have a key and a nonce. Which can be generated as in the example
below:</p>
<pre><code class="language-php " >use Framework\Crypto\SecretBox;
$key = SecretBox::makeKey(); // string
$nonce = SecretBox::makeNonce(); // string
</code></pre>
<p>With these two strings it will be possible to encrypt messages and decrypt
ciphertexts.</p>
<p>To do this, create an instance of the SecretBox class passing the key and nonce
in the constructor:</p>
<pre><code class="language-php " >$secretBox = new SecretBox($key, $nonce);
</code></pre>
<p>Once this is done, it is possible to encrypt messages:</p>
<pre><code class="language-php " >$message = &#039;Hello, Sodium!&#039;;
$ciphertext = $secretBox-&gt;encrypt($message); // string
</code></pre>
<p>And also decrypt:</p>
<pre><code class="language-php " >$message = $secretBox-&gt;decrypt($ciphertext); // string or false
</code></pre>
<p>Note that the <code>decrypt</code> method will return <code>false</code> if it fails to decrypt.</p>
</div>
<div class="section" id="sign">
<h2>Sign</h2>
<p>The <strong>Sign</strong> class allows you to create message signatures using secret keys and
verify message authenticity using public keys.</p>
<p>First, you must have a key pair to generate the secret and public keys:</p>
<pre><code class="language-php " >use Framework\Crypto\Sign;
$keyPair = Sign::makeKeyPair(); // string
</code></pre>
<p>Then, the secret key that will be used to create the message signature is
generated:</p>
<pre><code class="language-php " >$secretKey = Sign::makeSecretKey($keyPair); // string
</code></pre>
<p>Then the public key is generated. It is with it that the signature will be
verified:</p>
<pre><code class="language-php " >$publicKey = Sign::makePublicKey($keyPair); // string
</code></pre>
<p>Below, we have a message and we generate a signature for it, using the same
message and also the secret key:</p>
<pre><code class="language-php " >$message = &#039;Ai, aiaiai quiri qui uai&#039;;
$signature = Sign::signature($message, $secretKey); // string
</code></pre>
<p>The message, signature and public key can be sent to the verifier, which will
use them to verify that the signature is valid:</p>
<pre><code class="language-php " >if (Sign::verify($message, $signature, $publicKey)) {
    echo &#039;Signature is verified!&#039;;
} else {
    echo &#039;Error: Signature is not verified!&#039;;
}
</code></pre>
<p>Note that for this type of communication the secret key and the key pair should
be stored secretly.</p>
</div>
<div class="section" id="utils">
<h2>Utils</h2>
<p>The <strong>Utils</strong> class has conversion methods resistant to side-channel attacks for
<a href="#hexadecimal">Hexadecimal</a> and <a href="#base64">Base64</a>.</p>
<div class="section" id="hexadecimal">
<h3>Hexadecimal</h3>
<p>It is possible to convert a binary string to hexadecimal:</p>
<pre><code class="language-php " >use Framework\Crypto\Utils;
$string = &#039;foo&#039;;
$hex = Utils::bin2hex($string); // string
</code></pre>
<p>And also convert from hexadecimal to binary:</p>
<pre><code class="language-php " >$string = Utils::hex2bin($hex); // string
</code></pre>
</div>
<div class="section" id="base64">
<h3>Base64</h3>
<p>It is possible to convert a binary string to base64:</p>
<pre><code class="language-php " >use Framework\Crypto\Utils;
$string = &#039;foo&#039;;
$base64 = Utils::bin2base64($string); // string
</code></pre>
<p>And also convert from base64 to binary:</p>
<pre><code class="language-php " >$string = Utils::base642bin($base64); // string
</code></pre>
</div>
</div>
<div class="section" id="conclusion">
<h2>Conclusion</h2>
<p>Webisters Crypto Library is an easy-to-use tool for, beginners and experienced, PHP developers.<br>It is perfect for communicating with encrypted data and creating secure hashes.<br>The more you use it, the more you will learn.</p>
<div class="phpdocumentor-admonition -note ">
            <svg class="phpdocumentor-admonition__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path></svg>
                    <article>
        <p>Did you find something wrong?<br>Be sure to let us know about it with an
<a href="https://github.com/webisters/crypto/issues">issue</a>.<br>Thank you!</p>
    </article>
</div>
</div>
</div>
                <section data-search-results class="phpdocumentor-search-results phpdocumentor-search-results--hidden">
    <section class="phpdocumentor-search-results__dialog">
        <header class="phpdocumentor-search-results__header">
            <h2 class="phpdocumentor-search-results__title">Search results</h2>
            <button class="phpdocumentor-search-results__close"><i class="fas fa-times"></i></button>
        </header>
        <section class="phpdocumentor-search-results__body">
            <ul class="phpdocumentor-search-results__entries"></ul>
        </section>
    </section>
</section>
<?php
require_once __DIR__ . '/../../../includes/footer.php';
?>
